/* Auto-generated by generate-quickstart-data.js. Do not edit. */
window.__SEARCH_INDEX = [
  {
    "page": "Cadence AI Delivery Platform",
    "title": "Getting Started Guide",
    "level": "h1",
    "url": "guides/guides.html",
    "body": "Onboarding and installation guide for Cadence AI workspace: Git, Node.js, Python, Salesforce CLI, MCP connectors, and environment diagnostics."
  },
  {
    "page": "Cadence AI Delivery Platform",
    "title": "Spec-Driven Development (Spec Kit)",
    "level": "h1",
    "url": "workflow/workflow.html",
    "body": "7-Stage SDD Lifecycle: Constitution, Specify, Clarify, Plan, Tasks, Analyze, Implement with human verification gates and full traceability."
  },
  {
    "page": "Cadence AI Delivery Platform",
    "title": "Project Constitution & 5 Quality Gates",
    "level": "h1",
    "url": "index.html#governance",
    "body": "EBOAP Constitution: Static Analysis Gate (Code Analyzer), Coverage Gate (>=85% Apex, LWC, Flow), Environment Gate, E2E Gate (Playwright), Release Verification Gate. Principles I to VIII."
  },
  {
    "page": "Cadence AI Delivery Platform",
    "title": "MCP Servers & Integrations",
    "level": "h1",
    "url": "index.html#mcp",
    "body": "Salesforce MCP Server (@salesforce/mcp) with all toolsets (DevOps Center, LWC, Apex Tests, SOQL, GraphQL, Org tools) and Figma MCP Server for design-to-code."
  },
  {
    "page": "Cadence AI Delivery Platform",
    "title": "Nebula Logger Standard Observability",
    "level": "h2",
    "url": "skills/skills.html#category/nebula",
    "body": "Mandatory enterprise logging framework across Apex, LWC, Flow, and Integrations. Logger.entry(), transaction tags, scenario tracking, and retention."
  },
  {
    "page": "Cadence AI Delivery Platform",
    "title": "Frequently Asked Questions (FAQs)",
    "level": "h1",
    "url": "faqs/faqs.html",
    "body": "Frequently asked questions about Cadence AI workspace: setup, role workflows, Spec Kit, skills, safety, and troubleshooting."
  },
  {
    "page": "Skill: automation-flow-generate (Automation & Integrations)",
    "title": "/automation-flow-generate",
    "level": "h3",
    "url": "skills/skills.html#skill/automation-flow-generate",
    "body": "automation-flow-generate - Automation & Integrations: Specialized AI skill for automation flow generate."
  },
  {
    "page": "Skill: design-systems-slds-apply (LWC & SLDS)",
    "title": "/design-systems-slds-apply",
    "level": "h3",
    "url": "skills/skills.html#skill/design-systems-slds-apply",
    "body": "design-systems-slds-apply - LWC & SLDS: Specialized AI skill for design systems slds apply."
  },
  {
    "page": "Skill: design-systems-slds-validate (LWC & SLDS)",
    "title": "/design-systems-slds-validate",
    "level": "h3",
    "url": "skills/skills.html#skill/design-systems-slds-validate",
    "body": "design-systems-slds-validate - LWC & SLDS: Specialized AI skill for design systems slds validate."
  },
  {
    "page": "Skill: design-systems-slds2-migrate (LWC & SLDS)",
    "title": "/design-systems-slds2-migrate",
    "level": "h3",
    "url": "skills/skills.html#skill/design-systems-slds2-migrate",
    "body": "design-systems-slds2-migrate - LWC & SLDS: Specialized AI skill for design systems slds2 migrate."
  },
  {
    "page": "Skill: dx-code-analyzer-configure (DevOps & Quality)",
    "title": "/dx-code-analyzer-configure",
    "level": "h3",
    "url": "skills/skills.html#skill/dx-code-analyzer-configure",
    "body": "dx-code-analyzer-configure - DevOps & Quality: Specialized AI skill for dx code analyzer configure."
  },
  {
    "page": "Skill: dx-code-analyzer-custom-rule-create (DevOps & Quality)",
    "title": "/dx-code-analyzer-custom-rule-create",
    "level": "h3",
    "url": "skills/skills.html#skill/dx-code-analyzer-custom-rule-create",
    "body": "dx-code-analyzer-custom-rule-create - DevOps & Quality: Specialized AI skill for dx code analyzer custom rule create."
  },
  {
    "page": "Skill: dx-code-analyzer-run (DevOps & Quality)",
    "title": "/dx-code-analyzer-run",
    "level": "h3",
    "url": "skills/skills.html#skill/dx-code-analyzer-run",
    "body": "dx-code-analyzer-run - DevOps & Quality: Specialized AI skill for dx code analyzer run."
  },
  {
    "page": "Skill: dx-org-devhub-configure (DevOps & Quality)",
    "title": "/dx-org-devhub-configure",
    "level": "h3",
    "url": "skills/skills.html#skill/dx-org-devhub-configure",
    "body": "dx-org-devhub-configure - DevOps & Quality: Specialized AI skill for dx org devhub configure."
  },
  {
    "page": "Skill: dx-org-manage (DevOps & Quality)",
    "title": "/dx-org-manage",
    "level": "h3",
    "url": "skills/skills.html#skill/dx-org-manage",
    "body": "dx-org-manage - DevOps & Quality: Specialized AI skill for dx org manage."
  },
  {
    "page": "Skill: dx-org-permission-set-assign (DevOps & Quality)",
    "title": "/dx-org-permission-set-assign",
    "level": "h3",
    "url": "skills/skills.html#skill/dx-org-permission-set-assign",
    "body": "dx-org-permission-set-assign - DevOps & Quality: Specialized AI skill for dx org permission set assign."
  },
  {
    "page": "Skill: dx-org-shape-manage (DevOps & Quality)",
    "title": "/dx-org-shape-manage",
    "level": "h3",
    "url": "skills/skills.html#skill/dx-org-shape-manage",
    "body": "dx-org-shape-manage - DevOps & Quality: Specialized AI skill for dx org shape manage."
  },
  {
    "page": "Skill: dx-org-switch (DevOps & Quality)",
    "title": "/dx-org-switch",
    "level": "h3",
    "url": "skills/skills.html#skill/dx-org-switch",
    "body": "dx-org-switch - DevOps & Quality: Specialized AI skill for dx org switch."
  },
  {
    "page": "Skill: dx-org-trial-expiration-check (DevOps & Quality)",
    "title": "/dx-org-trial-expiration-check",
    "level": "h3",
    "url": "skills/skills.html#skill/dx-org-trial-expiration-check",
    "body": "dx-org-trial-expiration-check - DevOps & Quality: Specialized AI skill for dx org trial expiration check."
  },
  {
    "page": "Skill: experience-content-media-search (Content & Media)",
    "title": "/experience-content-media-search",
    "level": "h3",
    "url": "skills/skills.html#skill/experience-content-media-search",
    "body": "experience-content-media-search - Content & Media: Specialized AI skill for experience content media search."
  },
  {
    "page": "Skill: experience-content-media-stock-image-search (Content & Media)",
    "title": "/experience-content-media-stock-image-search",
    "level": "h3",
    "url": "skills/skills.html#skill/experience-content-media-stock-image-search",
    "body": "experience-content-media-stock-image-search - Content & Media: Specialized AI skill for experience content media stock image search."
  },
  {
    "page": "Skill: experience-lds-best-practices-apply (Salesforce Platform)",
    "title": "/experience-lds-best-practices-apply",
    "level": "h3",
    "url": "skills/skills.html#skill/experience-lds-best-practices-apply",
    "body": "experience-lds-best-practices-apply - Salesforce Platform: Specialized AI skill for experience lds best practices apply."
  },
  {
    "page": "Skill: experience-lds-data-requirements-generate (Salesforce Platform)",
    "title": "/experience-lds-data-requirements-generate",
    "level": "h3",
    "url": "skills/skills.html#skill/experience-lds-data-requirements-generate",
    "body": "experience-lds-data-requirements-generate - Salesforce Platform: Specialized AI skill for experience lds data requirements generate."
  },
  {
    "page": "Skill: experience-lds-graphql-generate (Salesforce Platform)",
    "title": "/experience-lds-graphql-generate",
    "level": "h3",
    "url": "skills/skills.html#skill/experience-lds-graphql-generate",
    "body": "experience-lds-graphql-generate - Salesforce Platform: Specialized AI skill for experience lds graphql generate."
  },
  {
    "page": "Skill: experience-lwc-accessibility-jest-run (LWC & SLDS)",
    "title": "/experience-lwc-accessibility-jest-run",
    "level": "h3",
    "url": "skills/skills.html#skill/experience-lwc-accessibility-jest-run",
    "body": "experience-lwc-accessibility-jest-run - LWC & SLDS: Specialized AI skill for experience lwc accessibility jest run."
  },
  {
    "page": "Skill: experience-lwc-base-components-integrate (LWC & SLDS)",
    "title": "/experience-lwc-base-components-integrate",
    "level": "h3",
    "url": "skills/skills.html#skill/experience-lwc-base-components-integrate",
    "body": "experience-lwc-base-components-integrate - LWC & SLDS: Specialized AI skill for experience lwc base components integrate."
  },
  {
    "page": "Skill: experience-lwc-design-generate (LWC & SLDS)",
    "title": "/experience-lwc-design-generate",
    "level": "h3",
    "url": "skills/skills.html#skill/experience-lwc-design-generate",
    "body": "experience-lwc-design-generate - LWC & SLDS: Specialized AI skill for experience lwc design generate."
  },
  {
    "page": "Skill: experience-lwc-generate (LWC & SLDS)",
    "title": "/experience-lwc-generate",
    "level": "h3",
    "url": "skills/skills.html#skill/experience-lwc-generate",
    "body": "experience-lwc-generate - LWC & SLDS: Specialized AI skill for experience lwc generate."
  },
  {
    "page": "Skill: experience-lwc-rtl-validate (LWC & SLDS)",
    "title": "/experience-lwc-rtl-validate",
    "level": "h3",
    "url": "skills/skills.html#skill/experience-lwc-rtl-validate",
    "body": "experience-lwc-rtl-validate - LWC & SLDS: Specialized AI skill for experience lwc rtl validate."
  },
  {
    "page": "Skill: experience-lwc-runtime-observe (LWC & SLDS)",
    "title": "/experience-lwc-runtime-observe",
    "level": "h3",
    "url": "skills/skills.html#skill/experience-lwc-runtime-observe",
    "body": "experience-lwc-runtime-observe - LWC & SLDS: Specialized AI skill for experience lwc runtime observe."
  },
  {
    "page": "Skill: experience-lwc-security-validate (LWC & SLDS)",
    "title": "/experience-lwc-security-validate",
    "level": "h3",
    "url": "skills/skills.html#skill/experience-lwc-security-validate",
    "body": "experience-lwc-security-validate - LWC & SLDS: Specialized AI skill for experience lwc security validate."
  },
  {
    "page": "Skill: experience-lwc-typescript-migrate (LWC & SLDS)",
    "title": "/experience-lwc-typescript-migrate",
    "level": "h3",
    "url": "skills/skills.html#skill/experience-lwc-typescript-migrate",
    "body": "experience-lwc-typescript-migrate - LWC & SLDS: Specialized AI skill for experience lwc typescript migrate."
  },
  {
    "page": "Skill: external-diagram-mermaid-generate (Architecture & Design)",
    "title": "/external-diagram-mermaid-generate",
    "level": "h3",
    "url": "skills/skills.html#skill/external-diagram-mermaid-generate",
    "body": "external-diagram-mermaid-generate - Architecture & Design: Specialized AI skill for external diagram mermaid generate."
  },
  {
    "page": "Skill: integration-connectivity-connected-app-configure (Automation & Integrations)",
    "title": "/integration-connectivity-connected-app-configure",
    "level": "h3",
    "url": "skills/skills.html#skill/integration-connectivity-connected-app-configure",
    "body": "integration-connectivity-connected-app-configure - Automation & Integrations: Specialized AI skill for integration connectivity connected app configure."
  },
  {
    "page": "Skill: integration-connectivity-generate (Automation & Integrations)",
    "title": "/integration-connectivity-generate",
    "level": "h3",
    "url": "skills/skills.html#skill/integration-connectivity-generate",
    "body": "integration-connectivity-generate - Automation & Integrations: Specialized AI skill for integration connectivity generate."
  },
  {
    "page": "Skill: integration-eventing-cdc-configure (Automation & Integrations)",
    "title": "/integration-eventing-cdc-configure",
    "level": "h3",
    "url": "skills/skills.html#skill/integration-eventing-cdc-configure",
    "body": "integration-eventing-cdc-configure - Automation & Integrations: Specialized AI skill for integration eventing cdc configure."
  },
  {
    "page": "Skill: integration-eventing-subscription-configure (Automation & Integrations)",
    "title": "/integration-eventing-subscription-configure",
    "level": "h3",
    "url": "skills/skills.html#skill/integration-eventing-subscription-configure",
    "body": "integration-eventing-subscription-configure - Automation & Integrations: Specialized AI skill for integration eventing subscription configure."
  },
  {
    "page": "Skill: nebula-logger-best-practices (Nebula Logger Observability)",
    "title": "/nebula-logger-best-practices",
    "level": "h3",
    "url": "skills/skills.html#skill/nebula-logger-best-practices",
    "body": "nebula-logger-best-practices - Nebula Logger Observability: Specialized AI skill for nebula logger best practices."
  },
  {
    "page": "Skill: nebula-logger-console (Nebula Logger Observability)",
    "title": "/nebula-logger-console",
    "level": "h3",
    "url": "skills/skills.html#skill/nebula-logger-console",
    "body": "nebula-logger-console - Nebula Logger Observability: Specialized AI skill for nebula logger console."
  },
  {
    "page": "Skill: nebula-logger-instrumentation (Nebula Logger Observability)",
    "title": "/nebula-logger-instrumentation",
    "level": "h3",
    "url": "skills/skills.html#skill/nebula-logger-instrumentation",
    "body": "nebula-logger-instrumentation - Nebula Logger Observability: Specialized AI skill for nebula logger instrumentation."
  },
  {
    "page": "Skill: nebula-logger-plugin-development (Nebula Logger Observability)",
    "title": "/nebula-logger-plugin-development",
    "level": "h3",
    "url": "skills/skills.html#skill/nebula-logger-plugin-development",
    "body": "nebula-logger-plugin-development - Nebula Logger Observability: Specialized AI skill for nebula logger plugin development."
  },
  {
    "page": "Skill: nebula-logger-purging-and-retention (Nebula Logger Observability)",
    "title": "/nebula-logger-purging-and-retention",
    "level": "h3",
    "url": "skills/skills.html#skill/nebula-logger-purging-and-retention",
    "body": "nebula-logger-purging-and-retention - Nebula Logger Observability: Specialized AI skill for nebula logger purging and retention."
  },
  {
    "page": "Skill: nebula-logger-testing-your-code (Nebula Logger Observability)",
    "title": "/nebula-logger-testing-your-code",
    "level": "h3",
    "url": "skills/skills.html#skill/nebula-logger-testing-your-code",
    "body": "nebula-logger-testing-your-code - Nebula Logger Observability: Specialized AI skill for nebula logger testing your code."
  },
  {
    "page": "Skill: platform-apex-anonymous-run (Apex & SOQL)",
    "title": "/platform-apex-anonymous-run",
    "level": "h3",
    "url": "skills/skills.html#skill/platform-apex-anonymous-run",
    "body": "platform-apex-anonymous-run - Apex & SOQL: Specialized AI skill for platform apex anonymous run."
  },
  {
    "page": "Skill: platform-apex-generate (Apex & SOQL)",
    "title": "/platform-apex-generate",
    "level": "h3",
    "url": "skills/skills.html#skill/platform-apex-generate",
    "body": "platform-apex-generate - Apex & SOQL: Specialized AI skill for platform apex generate."
  },
  {
    "page": "Skill: platform-apex-logs-debug (Apex & SOQL)",
    "title": "/platform-apex-logs-debug",
    "level": "h3",
    "url": "skills/skills.html#skill/platform-apex-logs-debug",
    "body": "platform-apex-logs-debug - Apex & SOQL: Specialized AI skill for platform apex logs debug."
  },
  {
    "page": "Skill: platform-apex-test-generate (Apex & SOQL)",
    "title": "/platform-apex-test-generate",
    "level": "h3",
    "url": "skills/skills.html#skill/platform-apex-test-generate",
    "body": "platform-apex-test-generate - Apex & SOQL: Specialized AI skill for platform apex test generate."
  },
  {
    "page": "Skill: platform-apex-test-run (Apex & SOQL)",
    "title": "/platform-apex-test-run",
    "level": "h3",
    "url": "skills/skills.html#skill/platform-apex-test-run",
    "body": "platform-apex-test-run - Apex & SOQL: Specialized AI skill for platform apex test run."
  },
  {
    "page": "Skill: platform-architecture-analyze (Architecture & Design)",
    "title": "/platform-architecture-analyze",
    "level": "h3",
    "url": "skills/skills.html#skill/platform-architecture-analyze",
    "body": "platform-architecture-analyze - Architecture & Design: Specialized AI skill for platform architecture analyze."
  },
  {
    "page": "Skill: platform-capability-search (Salesforce Platform)",
    "title": "/platform-capability-search",
    "level": "h3",
    "url": "skills/skills.html#skill/platform-capability-search",
    "body": "platform-capability-search - Salesforce Platform: Specialized AI skill for platform capability search."
  },
  {
    "page": "Skill: platform-custom-application-generate (Salesforce Platform)",
    "title": "/platform-custom-application-generate",
    "level": "h3",
    "url": "skills/skills.html#skill/platform-custom-application-generate",
    "body": "platform-custom-application-generate - Salesforce Platform: Specialized AI skill for platform custom application generate."
  },
  {
    "page": "Skill: platform-custom-field-generate (Salesforce Platform)",
    "title": "/platform-custom-field-generate",
    "level": "h3",
    "url": "skills/skills.html#skill/platform-custom-field-generate",
    "body": "platform-custom-field-generate - Salesforce Platform: ` | Always include | Explain the business reason *why* this field exists. | | `` | Always include | Actionable end-user guidance that adds value beyond the label (e.g., \"Enter the value in USD including tax\", not \"The amount\"). | `` and `` are man..."
  },
  {
    "page": "Skill: platform-custom-lightning-type-generate (Salesforce Platform)",
    "title": "/platform-custom-lightning-type-generate",
    "level": "h3",
    "url": "skills/skills.html#skill/platform-custom-lightning-type-generate",
    "body": "platform-custom-lightning-type-generate - Salesforce Platform: Specialized AI skill for platform custom lightning type generate."
  },
  {
    "page": "Skill: platform-custom-metadata-type-generate (DevOps & Quality)",
    "title": "/platform-custom-metadata-type-generate",
    "level": "h3",
    "url": "skills/skills.html#skill/platform-custom-metadata-type-generate",
    "body": "platform-custom-metadata-type-generate - DevOps & Quality: ` | Always include | What this type configures and who owns it | `` being **required here but forbidden on a custom setting** is the most commonly inverted rule between the two families. Neither failure mentions the other family's rule. ### Forbid..."
  },
  {
    "page": "Skill: platform-custom-object-generate (Salesforce Platform)",
    "title": "/platform-custom-object-generate",
    "level": "h3",
    "url": "skills/skills.html#skill/platform-custom-object-generate",
    "body": "platform-custom-object-generate - Salesforce Platform: ` stale, so you must refresh it (propose + confirm). This applies equally to validation-rule changes, not just fields. See Section 3.B. ## Specification ## 1. Overview and Purpose This document defines the mandatory constraints for generating Cust..."
  },
  {
    "page": "Skill: platform-custom-report-type-generate (Salesforce Platform)",
    "title": "/platform-custom-report-type-generate",
    "level": "h3",
    "url": "skills/skills.html#skill/platform-custom-report-type-generate",
    "body": "platform-custom-report-type-generate - Salesforce Platform: Specialized AI skill for platform custom report type generate."
  },
  {
    "page": "Skill: platform-custom-setting-generate (Salesforce Platform)",
    "title": "/platform-custom-setting-generate",
    "level": "h3",
    "url": "skills/skills.html#skill/platform-custom-setting-generate",
    "body": "platform-custom-setting-generate - Salesforce Platform: ` | Always include | Explain what the setting controls and who edits it | | `` | Optional | Accepted | | `` | Optional | Accepted — permitted despite `recordTypes` and `compactLayouts` being forbidden | ### Forbidden Elements Every element below p..."
  },
  {
    "page": "Skill: platform-custom-tab-generate (Salesforce Platform)",
    "title": "/platform-custom-tab-generate",
    "level": "h3",
    "url": "skills/skills.html#skill/platform-custom-tab-generate",
    "body": "platform-custom-tab-generate - Salesforce Platform: ` (optional) | | **Web tabs** | `` (required, set to `false`), `` (required), `` (required), `` (required), `` (required, set to `UTF-8`), `` (optional), `` (optional) | | **Visualforce tabs** | `` (required, set to `false`), `` (required), `` (re..."
  },
  {
    "page": "Skill: platform-data-and-tooling-api-context-get (Salesforce Platform)",
    "title": "/platform-data-and-tooling-api-context-get",
    "level": "h3",
    "url": "skills/skills.html#skill/platform-data-and-tooling-api-context-get",
    "body": "platform-data-and-tooling-api-context-get - Salesforce Platform: Specialized AI skill for platform data and tooling api context get."
  },
  {
    "page": "Skill: platform-data-manage (Salesforce Platform)",
    "title": "/platform-data-manage",
    "level": "h3",
    "url": "skills/skills.html#skill/platform-data-manage",
    "body": "platform-data-manage - Salesforce Platform: Specialized AI skill for platform data manage."
  },
  {
    "page": "Skill: platform-deploy-validate (DevOps & Quality)",
    "title": "/platform-deploy-validate",
    "level": "h3",
    "url": "skills/skills.html#skill/platform-deploy-validate",
    "body": "platform-deploy-validate - DevOps & Quality: Specialized AI skill for platform deploy validate."
  },
  {
    "page": "Skill: platform-destructive-deploy (DevOps & Quality)",
    "title": "/platform-destructive-deploy",
    "level": "h3",
    "url": "skills/skills.html#skill/platform-destructive-deploy",
    "body": "platform-destructive-deploy - DevOps & Quality: Specialized AI skill for platform destructive deploy."
  },
  {
    "page": "Skill: platform-docs-get (Salesforce Platform)",
    "title": "/platform-docs-get",
    "level": "h3",
    "url": "skills/skills.html#skill/platform-docs-get",
    "body": "platform-docs-get - Salesforce Platform: Specialized AI skill for platform docs get."
  },
  {
    "page": "Skill: platform-environment-validate (DevOps & Quality)",
    "title": "/platform-environment-validate",
    "level": "h3",
    "url": "skills/skills.html#skill/platform-environment-validate",
    "body": "platform-environment-validate - DevOps & Quality: Specialized AI skill for platform environment validate."
  },
  {
    "page": "Skill: platform-flexipage-generate (Salesforce Platform)",
    "title": "/platform-flexipage-generate",
    "level": "h3",
    "url": "skills/skills.html#skill/platform-flexipage-generate",
    "body": "platform-flexipage-generate - Salesforce Platform: Specialized AI skill for platform flexipage generate."
  },
  {
    "page": "Skill: platform-lightning-app-coordinate (Salesforce Platform)",
    "title": "/platform-lightning-app-coordinate",
    "level": "h3",
    "url": "skills/skills.html#skill/platform-lightning-app-coordinate",
    "body": "platform-lightning-app-coordinate - Salesforce Platform: Specialized AI skill for platform lightning app coordinate."
  },
  {
    "page": "Skill: platform-list-view-generate (Salesforce Platform)",
    "title": "/platform-list-view-generate",
    "level": "h3",
    "url": "skills/skills.html#skill/platform-list-view-generate",
    "body": "platform-list-view-generate - Salesforce Platform: Specialized AI skill for platform list view generate."
  },
  {
    "page": "Skill: platform-manifest-generate (DevOps & Quality)",
    "title": "/platform-manifest-generate",
    "level": "h3",
    "url": "skills/skills.html#skill/platform-manifest-generate",
    "body": "platform-manifest-generate - DevOps & Quality: Specialized AI skill for platform manifest generate."
  },
  {
    "page": "Skill: platform-metadata-api-context-get (DevOps & Quality)",
    "title": "/platform-metadata-api-context-get",
    "level": "h3",
    "url": "skills/skills.html#skill/platform-metadata-api-context-get",
    "body": "platform-metadata-api-context-get - DevOps & Quality: Specialized AI skill for platform metadata api context get."
  },
  {
    "page": "Skill: platform-metadata-deploy (DevOps & Quality)",
    "title": "/platform-metadata-deploy",
    "level": "h3",
    "url": "skills/skills.html#skill/platform-metadata-deploy",
    "body": "platform-metadata-deploy - DevOps & Quality: Specialized AI skill for platform metadata deploy."
  },
  {
    "page": "Skill: platform-metadata-retrieve (DevOps & Quality)",
    "title": "/platform-metadata-retrieve",
    "level": "h3",
    "url": "skills/skills.html#skill/platform-metadata-retrieve",
    "body": "platform-metadata-retrieve - DevOps & Quality: Specialized AI skill for platform metadata retrieve."
  },
  {
    "page": "Skill: platform-permission-set-generate (Salesforce Platform)",
    "title": "/platform-permission-set-generate",
    "level": "h3",
    "url": "skills/skills.html#skill/platform-permission-set-generate",
    "body": "platform-permission-set-generate - Salesforce Platform: Clear description of purpose and intended audience"
  },
  {
    "page": "Skill: platform-quick-deploy (DevOps & Quality)",
    "title": "/platform-quick-deploy",
    "level": "h3",
    "url": "skills/skills.html#skill/platform-quick-deploy",
    "body": "platform-quick-deploy - DevOps & Quality: Specialized AI skill for platform quick deploy."
  },
  {
    "page": "Skill: platform-report-generate (Salesforce Platform)",
    "title": "/platform-report-generate",
    "level": "h3",
    "url": "skills/skills.html#skill/platform-report-generate",
    "body": "platform-report-generate - Salesforce Platform: Specialized AI skill for platform report generate."
  },
  {
    "page": "Skill: platform-sandbox-configure (DevOps & Quality)",
    "title": "/platform-sandbox-configure",
    "level": "h3",
    "url": "skills/skills.html#skill/platform-sandbox-configure",
    "body": "platform-sandbox-configure - DevOps & Quality: Specialized AI skill for platform sandbox configure."
  },
  {
    "page": "Skill: platform-sharing-owd-configure (Salesforce Platform)",
    "title": "/platform-sharing-owd-configure",
    "level": "h3",
    "url": "skills/skills.html#skill/platform-sharing-owd-configure",
    "body": "platform-sharing-owd-configure - Salesforce Platform: Specialized AI skill for platform sharing owd configure."
  },
  {
    "page": "Skill: platform-sharing-rules-generate (Salesforce Platform)",
    "title": "/platform-sharing-rules-generate",
    "level": "h3",
    "url": "skills/skills.html#skill/platform-sharing-rules-generate",
    "body": "platform-sharing-rules-generate - Salesforce Platform: Specialized AI skill for platform sharing rules generate."
  },
  {
    "page": "Skill: platform-soql-query (Apex & SOQL)",
    "title": "/platform-soql-query",
    "level": "h3",
    "url": "skills/skills.html#skill/platform-soql-query",
    "body": "platform-soql-query - Apex & SOQL: Specialized AI skill for platform soql query."
  },
  {
    "page": "Skill: platform-validation-rule-generate (Salesforce Platform)",
    "title": "/platform-validation-rule-generate",
    "level": "h3",
    "url": "skills/skills.html#skill/platform-validation-rule-generate",
    "body": "platform-validation-rule-generate - Salesforce Platform: Specialized AI skill for platform validation rule generate."
  },
  {
    "page": "Skill: platform-value-set-generate (Salesforce Platform)",
    "title": "/platform-value-set-generate",
    "level": "h3",
    "url": "skills/skills.html#skill/platform-value-set-generate",
    "body": "platform-value-set-generate - Salesforce Platform: Specialized AI skill for platform value set generate."
  },
  {
    "page": "Skill: playwright-cli (E2E Testing)",
    "title": "/playwright-cli",
    "level": "h3",
    "url": "skills/skills.html#skill/playwright-cli",
    "body": "playwright-cli - E2E Testing: Specialized AI skill for playwright cli."
  },
  {
    "page": "Skill: service-email-to-case-configure (Automation & Integrations)",
    "title": "/service-email-to-case-configure",
    "level": "h3",
    "url": "skills/skills.html#skill/service-email-to-case-configure",
    "body": "service-email-to-case-configure - Automation & Integrations: Specialized AI skill for service email to case configure."
  },
  {
    "page": "Skill: speckit-analyze (Spec Kit (SDD))",
    "title": "/speckit.analyze",
    "level": "h3",
    "url": "skills/skills.html#skill/speckit-analyze",
    "body": "speckit-analyze - Spec Kit (SDD): Specialized AI skill for speckit analyze."
  },
  {
    "page": "Skill: speckit-bugfix-patch (Spec Kit (SDD))",
    "title": "/speckit.bugfix-patch",
    "level": "h3",
    "url": "skills/skills.html#skill/speckit-bugfix-patch",
    "body": "speckit-bugfix-patch - Spec Kit (SDD): Specialized AI skill for speckit bugfix patch."
  },
  {
    "page": "Skill: speckit-bugfix-report (Spec Kit (SDD))",
    "title": "/speckit.bugfix-report",
    "level": "h3",
    "url": "skills/skills.html#skill/speckit-bugfix-report",
    "body": "speckit-bugfix-report - Spec Kit (SDD): [User's bug description, clarified and structured]"
  },
  {
    "page": "Skill: speckit-bugfix-switch (Spec Kit (SDD))",
    "title": "/speckit.bugfix-switch",
    "level": "h3",
    "url": "skills/skills.html#skill/speckit-bugfix-switch",
    "body": "speckit-bugfix-switch - Spec Kit (SDD): Specialized AI skill for speckit bugfix switch."
  },
  {
    "page": "Skill: speckit-bugfix-verify (Spec Kit (SDD))",
    "title": "/speckit.bugfix-verify",
    "level": "h3",
    "url": "skills/skills.html#skill/speckit-bugfix-verify",
    "body": "speckit-bugfix-verify - Spec Kit (SDD): Specialized AI skill for speckit bugfix verify."
  },
  {
    "page": "Skill: speckit-checklist (Spec Kit (SDD))",
    "title": "/speckit.checklist",
    "level": "h3",
    "url": "skills/skills.html#skill/speckit-checklist",
    "body": "speckit-checklist - Spec Kit (SDD): Specialized AI skill for speckit checklist."
  },
  {
    "page": "Skill: speckit-clarify (Spec Kit (SDD))",
    "title": "/speckit.clarify",
    "level": "h3",
    "url": "skills/skills.html#skill/speckit-clarify",
    "body": "speckit-clarify - Spec Kit (SDD): Specialized AI skill for speckit clarify."
  },
  {
    "page": "Skill: speckit-constitution (Spec Kit (SDD))",
    "title": "/speckit.constitution",
    "level": "h3",
    "url": "skills/skills.html#skill/speckit-constitution",
    "body": "speckit-constitution - Spec Kit (SDD): Specialized AI skill for speckit constitution."
  },
  {
    "page": "Skill: speckit-converge (Spec Kit (SDD))",
    "title": "/speckit.converge",
    "level": "h3",
    "url": "skills/skills.html#skill/speckit-converge",
    "body": "speckit-converge - Spec Kit (SDD): Specialized AI skill for speckit converge."
  },
  {
    "page": "Skill: speckit-figma-starter-import (Spec Kit (SDD))",
    "title": "/speckit.figma-starter-import",
    "level": "h3",
    "url": "skills/skills.html#skill/speckit-figma-starter-import",
    "body": "speckit-figma-starter-import - Spec Kit (SDD): Specialized AI skill for speckit figma starter import."
  },
  {
    "page": "Skill: speckit-git-commit (Spec Kit (SDD))",
    "title": "/speckit.git-commit",
    "level": "h3",
    "url": "skills/skills.html#skill/speckit-git-commit",
    "body": "speckit-git-commit - Spec Kit (SDD): Specialized AI skill for speckit git commit."
  },
  {
    "page": "Skill: speckit-git-feature (Spec Kit (SDD))",
    "title": "/speckit.git-feature",
    "level": "h3",
    "url": "skills/skills.html#skill/speckit-git-feature",
    "body": "speckit-git-feature - Spec Kit (SDD): Specialized AI skill for speckit git feature."
  },
  {
    "page": "Skill: speckit-git-initialize (Spec Kit (SDD))",
    "title": "/speckit.git-initialize",
    "level": "h3",
    "url": "skills/skills.html#skill/speckit-git-initialize",
    "body": "speckit-git-initialize - Spec Kit (SDD): Specialized AI skill for speckit git initialize."
  },
  {
    "page": "Skill: speckit-git-remote (Spec Kit (SDD))",
    "title": "/speckit.git-remote",
    "level": "h3",
    "url": "skills/skills.html#skill/speckit-git-remote",
    "body": "speckit-git-remote - Spec Kit (SDD): Specialized AI skill for speckit git remote."
  },
  {
    "page": "Skill: speckit-git-validate (Spec Kit (SDD))",
    "title": "/speckit.git-validate",
    "level": "h3",
    "url": "skills/skills.html#skill/speckit-git-validate",
    "body": "speckit-git-validate - Spec Kit (SDD): Specialized AI skill for speckit git validate."
  },
  {
    "page": "Skill: speckit-implement (Spec Kit (SDD))",
    "title": "/speckit.implement",
    "level": "h3",
    "url": "skills/skills.html#skill/speckit-implement",
    "body": "speckit-implement - Spec Kit (SDD): Specialized AI skill for speckit implement."
  },
  {
    "page": "Skill: speckit-iterate-apply (Spec Kit (SDD))",
    "title": "/speckit.iterate-apply",
    "level": "h3",
    "url": "skills/skills.html#skill/speckit-iterate-apply",
    "body": "speckit-iterate-apply - Spec Kit (SDD): Specialized AI skill for speckit iterate apply."
  },
  {
    "page": "Skill: speckit-iterate-define (Spec Kit (SDD))",
    "title": "/speckit.iterate-define",
    "level": "h3",
    "url": "skills/skills.html#skill/speckit-iterate-define",
    "body": "speckit-iterate-define - Spec Kit (SDD): Specialized AI skill for speckit iterate define."
  },
  {
    "page": "Skill: speckit-plan (Spec Kit (SDD))",
    "title": "/speckit.plan",
    "level": "h3",
    "url": "skills/skills.html#skill/speckit-plan",
    "body": "speckit-plan - Spec Kit (SDD): Specialized AI skill for speckit plan."
  },
  {
    "page": "Skill: speckit-specify (Spec Kit (SDD))",
    "title": "/speckit.specify",
    "level": "h3",
    "url": "skills/skills.html#skill/speckit-specify",
    "body": "speckit-specify - Spec Kit (SDD): Specialized AI skill for speckit specify."
  },
  {
    "page": "Skill: speckit-tasks (Spec Kit (SDD))",
    "title": "/speckit.tasks",
    "level": "h3",
    "url": "skills/skills.html#skill/speckit-tasks",
    "body": "speckit-tasks - Spec Kit (SDD): Specialized AI skill for speckit tasks."
  },
  {
    "page": "Skill: speckit-taskstoissues (Spec Kit (SDD))",
    "title": "/speckit.taskstoissues",
    "level": "h3",
    "url": "skills/skills.html#skill/speckit-taskstoissues",
    "body": "speckit-taskstoissues - Spec Kit (SDD): Specialized AI skill for speckit taskstoissues."
  },
  {
    "page": "Persona: the Project Manager",
    "title": "the Project Manager Role Journey & Prompts",
    "level": "h2",
    "url": "index.html#personas",
    "body": "Governs scope, project constitution, delivery milestones, and quality gates across all phases of Spec-Driven Development. Every scope decision grounded in the Project Constitution, every work item linked to business requirements. Deliver with end-to-end traceability. Key value: Prevents scope creep with automated Spec Kit consistency checks. Enforces Constitution Principle VIII (Human-Gated AI Delivery). Generates stakeholder-ready milestone and status reports with live metadata evidence"
  },
  {
    "page": "Persona: the Product Owner",
    "title": "the Product Owner Role Journey & Prompts",
    "level": "h2",
    "url": "index.html#personas",
    "body": "Shapes requirements, clarifies edge cases, validates user journeys, and governs business value using Spec Kit and Figma MCP. Bridge Figma designs and business rules into unambiguous Gherkin acceptance criteria, verified against live Salesforce metadata. Key value: Imports Figma design nodes directly into structured user stories. Eliminates ambiguity early via targeted AI clarification questions. Enforces multilingual (EN/SV) requirements from day one"
  },
  {
    "page": "Persona: the Developer",
    "title": "the Developer Role Journey & Prompts",
    "level": "h2",
    "url": "index.html#personas",
    "body": "Builds enterprise Salesforce solutions (Apex, LWC, Flow, Metadata) with Nebula Logger, Code Analyzer, and Salesforce MCP. Clean, bulkified, secure Salesforce code following the 5 Quality Gates, complete with unit tests and structured logging. Key value: Generates production-grade Apex with TestDataFactory and ≥85% code coverage. Builds accessible LWCs with Lightning Base Components and SLDS styling hooks. Mandatory structured observability via Nebula Logger on all custom logic"
  },
  {
    "page": "Persona: the QA Engineer",
    "title": "the QA Engineer Role Journey & Prompts",
    "level": "h2",
    "url": "index.html#personas",
    "body": "Guarantees multi-layer quality across Apex unit tests, LWC Jest, Sa11y accessibility, and Playwright E2E suites. End-to-end quality assurance from individual LWC Jest assertions to full Playwright browser automation. Key value: Automates Playwright E2E tests matching Gherkin user stories. Executes Sa11y Jest accessibility tests for WCAG 2.2 AA compliance. Verifies Apex code coverage thresholds (≥85%) across all classes"
  },
  {
    "page": "Persona: the Technical Architect",
    "title": "the Technical Architect Role Journey & Prompts",
    "level": "h2",
    "url": "index.html#personas",
    "body": "Guards architectural integrity, Salesforce Well-Architected compliance, scalability, security, and integration topology. Evaluate solutions against Trusted, Easy, and Adaptable pillars with automated architecture reviews and Mermaid diagrams. Key value: Holistic code and metadata health reports mapped to Well-Architected. Automatic Mermaid architectural and ERD diagram generation. Validates Org-Wide Defaults, Sharing Rules, and security boundaries"
  },
  {
    "page": "Persona: the Release Manager",
    "title": "the Release Manager Role Journey & Prompts",
    "level": "h2",
    "url": "index.html#personas",
    "body": "Orchestrates sandbox deployments, quick deploys, package manifests, and release gate verification. Zero-surprise deployments with dry-run validation, package.xml generation, and automated release checklists. Key value: Dry-run deployment validation before touching production. Automated package.xml and destructiveChanges.xml generation. Validates all 5 Quality Gates before production release sign-off"
  }
];
